.idea/.gitignore
.idea/material_theme_project_new.xml
src/App.js
src/components/common/buttons/MtButtons.js
src/components/common/buttons/MtButtons.module.scss

:art: Create component MtButtons

:art: Create component MtButtons

---

src/App.js
src/assets/css/common.css
src/config/route-config.js
src/layout/Header.js
src/layout/RootLayout.js
src/pages/chat/Chat.js
src/pages/error/ErrorPage.js

RootLayout 파일 추가
route-config 기본형 파일 추가

✅RootLayout, route-config 파일 추가

---

src/App.js
src/assets/css/common.css
src/assets/images/icons/icon-correct.svg
src/assets/images/icons/icon-error.svg
src/components/common/inputs/DefaultInput.js
src/components/common/inputs/DefaultInput.module.scss

Jin input 

---

src/assets/css/common.css
src/components/common/inputs/DefaultInput.js
src/config/route-config.js
src/pages/main/MainFilter.js

common css 수정 & input placeholder 추가

✅common css 수정 & input placeholder 추가

---

src/assets/css/common.css
src/layout/Header.module.scss
src/pages/chat/Chat.js
src/pages/chat/Chat.module.scss
src/pages/chat/components/ChatBody.js
src/pages/chat/components/ChatHead.js
src/pages/chat/components/ChatInput.js
src/pages/chat/components/ChatMenu.js

:ambulance: 레이어 비활성화 수정

---

src/components/common/inputs/DefaultInput.js

input onChange 추가

---

src/components/common/buttons/MtButtons.js
src/components/common/buttons/MtButtons.module.scss
src/components/common/inputs/DefaultInput.js
src/config/route-config.js
src/pages/login/LoginPage.js
src/pages/login/LoginPage.module.scss
src/pages/signUp/SignUp.js
src/pages/signUp/components/EmailInput.js
src/pages/signUp/components/EmailInput.module.scss
src/pages/signUp/components/MajorInput.js
src/pages/signUp/components/VerificationInput.js

:white_check_mark: fix input(disabled)

:art: Create SignUpPage & fix LoginPage

---

src/config/route-config.js

🐛router Error fix

---

src/assets/css/reset.css
src/components/common/buttons/checkboxbutton/Checkbox.jsx
src/components/common/buttons/checkboxbutton/Checkbox.module.scss
src/components/common/buttons/checkboxbutton/CheckboxButtonGroup.jsx
src/components/common/buttons/radiobutton/Radio.module.scss
src/config/route-config.js
src/layout/RootLayout.js

✅ feat : checkbox button 구현

---

.idea/inspectionProfiles/Project_Default.xml
src/components/common/buttons/MtButtons.js
src/pages/login/LoginPage.js
src/pages/login/LoginPage.module.scss
src/pages/signUp/SignUp.js
src/pages/signUp/components/EmailInput.js
src/pages/signUp/components/EmailInput.module.scss
src/pages/signUp/components/MajorInput.js
src/pages/signUp/components/PasswordInput.jsx
src/pages/signUp/components/PrivacyInfoInput.jsx
src/pages/signUp/components/SignUpComplete.jsx
src/pages/signUp/components/VerificationInput.js

Jinu sign up page

---

src/pages/error/ErrorPage.module.scss
src/pages/group/GroupCreate.module.scss
src/pages/login/components/FirstLoginNickName.module.scss
src/pages/login/components/FirstLoginProfile.module.scss
src/pages/mypage/components/ActionSection.module.scss
src/pages/mypage/components/ProfileSection.module.scss

에러, 마이페이지 메인, 그룹생성페이지
px -> carc로 전면 수정완료

✅ px -> carc로 전면 수정완료

---

src/config/route-config.js

:white_check_mark: 라우트 업데이트

---

src/pages/main/Main.js
src/pages/main/Main.module.scss
src/pages/main/components/MainFilter.module.scss
src/pages/main/components/MeetingList.module.scss
src/pages/main/components/RegionFilter.module.scss
src/pages/mypage/components/ActionSection.jsx

:lipstick: 메인페이지 필터 ui 수정:

---

.gitignore
src/pages/login/LoginPage.js
src/pages/sign_up/SignUp.js
src/pages/sign_up/components/SignUpComplete.jsx
src/pages/sign_up/components/create_email/CreateEmail.jsx
src/pages/sign_up/components/create_email/EmailInput.jsx
src/pages/sign_up/components/create_email/MajorInput.jsx
src/pages/sign_up/components/create_email/VerificationInput.jsx
src/pages/sign_up/components/create_informations/CreateInformation.jsx
src/pages/sign_up/components/create_password/CreatePassword.jsx

✅ 회원가입, 로그인 1차 완료

---

src/layout/components/FloatingNavigation.jsx
src/pages/login/LoginPage.js
src/pages/login/components/FirstLoginNickName.jsx
src/pages/login/components/FirstLoginProfile.jsx
src/pages/sign_up/SignUp.js
src/pages/sign_up/components/SignUpComplete.jsx
src/pages/sign_up/components/create_email/VerificationInput.jsx
src/pages/sign_up/components/create_informations/CreateInformation.jsx

✅프로필, 닉네임 설정 완료

---

src/components/common/groupBoxs/GroupBox.jsx
src/components/common/groupBoxs/RequestBtns.jsx
src/layout/Header.js
src/layout/Header.module.scss
src/layout/components/FloatingNavigation.jsx
src/pages/chat/Chat.module.scss
src/pages/group/Group.js
src/pages/group/Group.module.scss
src/pages/group/components/GroupViewBody.jsx
src/pages/mypage/components/ProfileSection.jsx
src/pages/mypage/components/ProfileSection.module.scss

- 그룹 초대링크 복사 ui 수정
- 마이페이지 ui 수정
- 헤더 ui 수정
-  매칭 신청, 거절 구현

Mimi redux1

---

src/layout/Header.js
src/pages/login/LoginPage.js
src/pages/login/LoginPage.module.scss
src/pages/sign_up/components/SignUpComponent.module.scss
src/pages/sign_up/components/create_email/CreateEmail.jsx
src/pages/sign_up/components/create_email/EmailInput.jsx
src/pages/sign_up/components/create_email/VerificationInput.jsx
src/pages/sign_up/components/create_informations/CreateInformation.jsx

- 회원가입 - 인증번호 전송 후 이메일,대학 수정 금지 (완)
- 인증코드 틀렸을 시 에러 처리 (완)
- 자동로그인 ui 수정 (완)
- 탈퇴한 아이디 로그인 안되게 (완)
- 회원가입 나이 제한 - 20세 이상(성인) (완)
- 회원가입창 헤더 안뜨게 설정 (완)

🐛 회원가입 입력시 disabled설정, 탈퇴 조건 추가, 나이제한 설정,  ui 수정

---

src/pages/mypage/components/ActionSection.jsx
src/pages/mypage/components/ActionSection.module.scss
src/pages/mypage/components/ProfileSection.jsx

- 마이페이지 회원정보 조회 및 수정, 충돌 해결
- 마이페이지 회원탈퇴 메뉴 UI 생성

✅ 마이페이지 회원정보 조회 및 수정, 충돌 해결 / 회원탈퇴 메뉴 UI 생성

---

src/pages/mypage/modify_information/components/EmailInput.jsx
src/pages/mypage/modify_information/components/VerificationInput.jsx
src/pages/mypage/modify_information/withdraw/Withdraw.js

🐛 회원탈퇴 WIP

---

src/pages/mypage/components/ProfileSection.jsx

:white_check_mark
